### ISSUE TITLE
This needs some updates to work with the latest Stripe api changes

### ISSUE THREAD

**Issue by tfarina** [yeargin/php-stripe-donations-form#1]
This requires some changes to work with github.com/stripe/stripe-php

**Comment by stephenyeargin** [comment]
Interesting. Guessing there are a handful of changes pertaining to [the API upgrades](https://stripe.com/docs/upgrades). Also just noticed this version commits the entire vendor library, which probably should be left to Composer to handle (and locked to a version).

@tfarina Did you run into issues loading a new version of the SDK, or with the one that is included currently?

**Comment by tfarina** [comment]
with the new version of the SDK. Needed some changes like:

Stripe::setApiKey -> \Stripe\Stripe::setApiKey
Stripe_Charge::create -> \Stripe\Charge::create

**Comment by stephenyeargin** [comment]
Cool. I need to update the install instructions to require `composer` (I think that's common enough now to go ahead and add that as a required step), remove the version stored in the repository, lock it to the new version in the `composer.json` file and fix issues from there.

Thanks for reporting the issue!

**Comment by stephenyeargin** [comment]
Fixed in #2. Ran a test transaction through it and got data.

**Comment by tfarina** [comment]
Thanks! You may close this if you wish.
